---
- name: Create ACI TN AP EPG 
  hosts: "aci"
  gather_facts: no

  tasks:
    - name: Create Tenant
      aci_tenant:
        host: "{{ ansible_host }}"
        use_ssl: yes
        validate_certs: false
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        tenant: "{{ tenant_name }}"
        description: "{{ description }}"
        state: "{{ action }}"
      register: result

    - name: Display the result
      debug:
        var: result
