- hosts: all
  tasks:
    - name: CREATE ACI TENANT 
      aci_tenant:
        hostname: 192.168.1.240
        username: admin
        password: password1234
        tenant: "TEST2"
        description: "test2"
        use_ssl: yes
        validate_certs: false
        state: "present"
