---
- name: Remove ACI EPG
  hosts: "aci"
  gather_facts: no

  tasks:
    - name: Remove EPG
      aci_epg:
        host: "{{ ansible_host }}"
        use_ssl: yes
        validate_certs: false
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        tenant: "{{ tenant_name }}"
        ap: "{{ ap_name }}"
        epg: "{{ epg_name }}"
        state: absent
      register: epg_result

    - name: Display the result
      debug:
        var: epg_result

    - name: Check if the Application Profile is empty
      aci_ap:
        host: "{{ ansible_host }}"
        use_ssl: yes
        validate_certs: false
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        tenant: "{{ tenant_name }}"
        ap: "{{ ap_name }}"
      register: ap_result
      ignore_errors: yes

    - name: Remove Application Profile if it's empty
      when: ap_result is succeeded
      aci_ap:
        host: "{{ ansible_host }}"
        use_ssl: yes
        validate_certs: false
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        tenant: "{{ tenant_name }}"
        ap: "{{ ap_name }}"
        state: absent
      register: ap_removal_result

    - name: Display the result
      debug:
        var: ap_removal_result

    - name: Remove BD
      aci_bd:
        host: "{{ ansible_host }}"
        use_ssl: yes
        validate_certs: false
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        tenant: "{{ tenant_name }}"
        bd: "{{ bd_name }}"
        state: absent
      register: bd_result

    - name: Display the result
      debug:
        var: bd_result
