---
- name: Remove ACI EPGs and APs
  hosts: "aci"
  gather_facts: no
  vars:
    state: absent  # Set the state variable to "absent" or "present" as needed


  tasks:
    - name: Remove BD
      aci_bd:
        host: "{{ ansible_host }}"
        use_ssl: yes
        validate_certs: false
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        tenant: "{{ tenant_name }}"
        bd: "{{ bd_name }}"
        state: "{{ state }}"
      register: bd_result

    - name: Display the result
      debug:
        var: bd_result



    - name: Remove EPG
      aci_epg:
        host: "{{ ansible_host }}"
        use_ssl: yes
        validate_certs: false
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        tenant: "{{ tenant_name }}"
        ap: "{{ ap_name }}"
        epg: "{{ epg_name }}"
        state: "{{ state }}"
      register: epg_result

    - name: Display the result
      debug:
        var: epg_result

    - name: Ensure epg_list is available
      set_fact:
        epg_list: []


    - name: Get a list of EPGs in the Application Profile
      aci_epg:
        host: "{{ ansible_host }}"
        use_ssl: yes
        validate_certs: false
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        tenant: "{{ tenant_name }}"
        ap: "{{ ap_name }}"
        state: query
      register: epg_list
      ignore_errors: yes

    - name: Display the result
      debug:
        var: epg_list 

    - name: Count child EPGs in the registered list
      set_fact:
#        child_epgs_count: "{{ epg_list | list | length }}"
#        child_epgs_count: "{{ epg_list.fvAp[0].children | selectattr('fvAEPg.0.state', 'eq', 'absent') | list | length }}"
        child_epgs_count: "{{ epg_list['fvAp']['children'][fvAEPg][name] |list | length }}"

      

    - name: Display child EPGs count
      debug:
        msg: "Child EPGs count in AP: {{ child_epgs_count }}"

