---
- hosts: all
  tasks:
    - name: Get hostname
      shell: echo $HOSTNAME
      register: result

    - debug:
        var: result

  shell: echo {{ ansible_hostname }}
  register: result

- debug:
    var: result
